name: Compile LaTeX document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v2
      with:
        root_file: background.tex

    - name: Compile LaTeX document
      run: latexmk -pdf -interaction=nonstopmode background.tex

    - name: List files in workspace
      run: ls -la

    - name: Create docs folder
      run: mkdir -p docs

    - name: Move PDF to docs folder
      run: mv background.pdf docs/

    - name: List files in docs folder
      run: ls -la docs/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/background.pdf
        git commit -m "Add compiled PDF"
        git push
